//=========================================================
// inc/InitDevice.h: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================
#ifndef __INIT_DEVICE_H__
#define __INIT_DEVICE_H__

// USER CONSTANTS
// USER PROTOTYPES

// $[Mode Transition Prototypes]
void enter_DefaultMode_from_RESET(void);
// [Mode Transition Prototypes]$

// $[Config(Per-Module Mode)Transition Prototypes]
// void WDT_0_enter_DefaultMode_from_RESET(void);
void VREG_0_enter_DefaultMode_from_RESET(void);
void CLOCK_0_enter_DefaultMode_from_RESET(void);
void PORTS_0_enter_DefaultMode_from_RESET(void);
void PORTS_1_enter_DefaultMode_from_RESET(void);
void PBCFG_0_enter_DefaultMode_from_RESET(void);
void HFOSC_0_enter_DefaultMode_from_RESET(void);
void CIP51_0_enter_DefaultMode_from_RESET(void);
void TIMER01_0_enter_DefaultMode_from_RESET(void);
void TIMER16_2_enter_DefaultMode_from_RESET(void);
void TIMER16_3_enter_DefaultMode_from_RESET(void);
void TIMER_SETUP_0_enter_DefaultMode_from_RESET(void);
void PCA_0_enter_DefaultMode_from_RESET(void);
void PCACH_0_enter_DefaultMode_from_RESET(void);
void PCACH_1_enter_DefaultMode_from_RESET(void);
void PCACH_2_enter_DefaultMode_from_RESET(void);
void SMBUS_0_enter_DefaultMode_from_RESET(void);
void UART_0_enter_DefaultMode_from_RESET(void);
void INTERRUPT_0_enter_DefaultMode_from_RESET(void);
//extern void USBLIB_0_enter_DefaultMode_from_RESET(void);
// [Config(Per-Module Mode)Transition Prototypes]$
#endif

